verbose = true

max-concurrency = 8

exclude = [
  "adlic.rjfun.com",
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd/",
  "https://github.com/admob-plus/admob-plus/blob/",
  "https://github.com/admob-plus/admob-plus/edit/",
  "https://github.com/admob-plus/admob-plus/tree/",
]
